import type { UniverseRole } from '../components/investment-universe/universeUi';

export type LiquidityLevel = 'High' | 'Medium' | 'Medium–low' | 'Low' | 'Very low';
export type Orientation = 'Growth' | 'Income' | 'Mixed' | 'Preservation' | 'Speculative';

export interface InvestmentCategory {
  id: string;
  name: string;
  group: 'traditional' | 'alternative' | 'niche';
  definition: string;
  howItWorks: string;
  returnDriver: string;
  riskProfile: string;
  liquidity: LiquidityLevel;
  orientation: Orientation;
  portfolioRole: UniverseRole;
  useCase: string;
  examples: string;
  volatility: string;
  growthPotential: string;
  inflationHedge: string;
  complexity: string;
  accessibility: string;
  holdingPeriod: string;
  valuationDifficulty: string;
  taxComplexity: string;
  deepDive: string[];
  /** 0–100 for spectrum charts */
  risk: number;
  liquidityScore: number;
  growth: number;
  income: number;
  complexityScore: number;
  accessibilityScore: number;
  alternativeScore: number;
}

export const INVESTMENT_CATEGORIES: InvestmentCategory[] = [
  {
    id: 'global-equities',
    name: 'Global equities',
    group: 'traditional',
    definition: 'Ownership stakes in publicly listed companies traded on stock exchanges worldwide.',
    howItWorks: 'You buy shares (directly or via funds/ETFs). Returns come from price appreciation, dividends, and sometimes buybacks. Exposure can be broad (global index) or targeted (sectors, regions, factors).',
    returnDriver: 'Corporate earnings growth, economic expansion, risk appetite, and currency moves for foreign listings.',
    riskProfile: 'Moderate to high over short horizons; primary long-term growth engine with drawdowns.',
    liquidity: 'High',
    orientation: 'Growth',
    portfolioRole: 'Core',
    useCase: 'Long-term wealth building, retirement funding, and participation in global economic growth.',
    examples: 'MSCI World ETF, S&P 500, EM equities, sector ETFs, individual large-cap stocks',
    volatility: 'Medium–high (single stocks higher than diversified funds)',
    growthPotential: 'High over multi-decade horizons',
    inflationHedge: 'Moderate (real earnings can rise with inflation over time)',
    complexity: 'Low–medium for diversified funds; higher for single-stock selection',
    accessibility: 'High via brokers and pension wrappers',
    holdingPeriod: '5–30+ years typical for strategic allocation',
    valuationDifficulty: 'Low for listed funds; medium for individual securities',
    taxComplexity: 'Varies by jurisdiction (withholding, capital gains, dividend treatment)',
    deepDive: [
      'Equities represent residual ownership: after debt and expenses, shareholders participate in profits and asset value.',
      'A global equity core reduces home-country bias and captures diversification across regions, sectors, and currencies.',
      'For most wealth-building goals, equities belong in the core allocation—not as a tactical side bet—subject to horizon and risk tolerance.',
    ],
    risk: 62,
    liquidityScore: 95,
    growth: 88,
    income: 35,
    complexityScore: 25,
    accessibilityScore: 92,
    alternativeScore: 8,
  },
  {
    id: 'fx',
    name: 'FX / foreign exchange',
    group: 'traditional',
    definition: 'Markets for exchanging one currency for another, including spot, forwards, and related macro exposures.',
    howItWorks: 'Participants trade currency pairs based on interest-rate differentials, trade flows, inflation, and policy. Leverage is common in retail FX; institutions use FX for hedging cross-border cash flows.',
    returnDriver: 'Relative monetary policy, inflation differentials, growth surprises, geopolitical shocks, and carry (interest differential).',
    riskProfile: 'Highly variable; can be low volatility when used as a hedge, high when traded speculatively with leverage.',
    liquidity: 'High',
    orientation: 'Speculative',
    portfolioRole: 'Tactical',
    useCase: 'Hedging foreign assets/income, short-term macro views, or liquidity management—not a standard compounding vehicle for most households.',
    examples: 'EUR/USD spot, CHF hedging, EM FX, currency-hedged share classes',
    volatility: 'High for speculative trading; lower when used as a hedge overlay',
    growthPotential: 'Not a reliable long-term compounder for most investors',
    inflationHedge: 'Indirect (currency may reflect inflation differentials)',
    complexity: 'Medium–high',
    accessibility: 'High for spot via banks/brokers; leveraged retail FX is widely available but risky',
    holdingPeriod: 'Days to months for tactical; ongoing for structural hedges',
    valuationDifficulty: 'Macro-driven; no “fair value” like equities',
    taxComplexity: 'Often nuanced (trading vs hedging characterisation)',
    deepDive: [
      'FX is essential for international investing but is not the same as owning productive assets.',
      'Carry and momentum strategies exist, yet costs, leverage, and regime shifts can erase edge quickly.',
      'For long-term wealth builders, FX is usually a hedge or implementation detail—not a core return source.',
    ],
    risk: 70,
    liquidityScore: 98,
    growth: 25,
    income: 20,
    complexityScore: 68,
    accessibilityScore: 85,
    alternativeScore: 35,
  },
  {
    id: 'fixed-income',
    name: 'Fixed income',
    group: 'traditional',
    definition: 'Debt instruments where investors lend capital to governments, agencies, or corporations for scheduled interest and principal repayment.',
    howItWorks: 'Bonds trade with prices inverse to yields. Funds/ETFs pool many issues. Duration measures sensitivity to rate changes. Credit quality affects default risk.',
    returnDriver: 'Coupon income, yield changes, credit spreads, and inflation expectations.',
    riskProfile: 'Generally lower than equities; rises with credit risk, long duration, or EM exposure.',
    liquidity: 'High',
    orientation: 'Income',
    portfolioRole: 'Income / defensive',
    useCase: 'Stability, income, liability matching, and diversification versus equities.',
    examples: 'Government bonds, investment-grade corporates, T-bills, bond ETFs, inflation-linked bonds',
    volatility: 'Low–medium (higher for long duration or high-yield)',
    growthPotential: 'Moderate nominal; real returns depend on inflation and starting yields',
    inflationHedge: 'Low unless inflation-linked; rising rates can hurt nominal bonds',
    complexity: 'Low–medium',
    accessibility: 'High',
    holdingPeriod: '1–15 years aligned with liability horizon',
    valuationDifficulty: 'Low–medium (yield-based)',
    taxComplexity: 'Coupon taxation; some jurisdictions favour certain bond types',
    deepDive: [
      'Fixed income anchors portfolios when equities fall, especially high-quality short-to-intermediate government debt.',
      'In low-yield environments, return potential is limited; credit stretching increases tail risk.',
      'Role is defensive and income-oriented—not primary long-term growth for most affluent accumulators.',
    ],
    risk: 28,
    liquidityScore: 90,
    growth: 35,
    income: 85,
    complexityScore: 30,
    accessibilityScore: 90,
    alternativeScore: 12,
  },
  {
    id: 'cash',
    name: 'Cash / money market',
    group: 'traditional',
    definition: 'Highly liquid short-term deposits, treasury bills, and money-market instruments prioritising capital stability and access.',
    howItWorks: 'You earn a floating short rate with minimal price movement. Used for reserves, near-term spending, and dry powder—not long-term growth.',
    returnDriver: 'Central bank policy rates and money-market spreads.',
    riskProfile: 'Very low credit/market risk in high-quality instruments; inflation erodes real value.',
    liquidity: 'High',
    orientation: 'Preservation',
    portfolioRole: 'Income / defensive',
    useCase: 'Emergency reserves, upcoming purchases, and temporary parking—not wealth compounding.',
    examples: 'Savings accounts, T-bills, money-market funds, overnight deposits',
    volatility: 'Very low',
    growthPotential: 'Low; tracks short rates',
    inflationHedge: 'Poor over long horizons',
    complexity: 'Low',
    accessibility: 'Very high',
    holdingPeriod: 'Days to 2 years',
    valuationDifficulty: 'Trivial',
    taxComplexity: 'Usually straightforward',
    deepDive: [
      'Cash is operational, not strategic growth capital—except when rates are unusually attractive.',
      'Excess cash beyond reserves creates drag versus productive assets.',
    ],
    risk: 5,
    liquidityScore: 100,
    growth: 10,
    income: 55,
    complexityScore: 8,
    accessibilityScore: 100,
    alternativeScore: 5,
  },
  {
    id: 'precious-metals',
    name: 'Precious metals',
    group: 'traditional',
    definition: 'Physical or financial exposure to gold, silver, platinum, and related commodities often viewed as monetary or crisis assets.',
    howItWorks: 'Hold bullion, allocated storage, or ETFs/ETCs backed by metal. Price driven by real rates, USD, jewellery/industrial demand, and risk-off flows.',
    returnDriver: 'Monetary conditions, inflation expectations, geopolitical stress, and supply/demand.',
    riskProfile: 'Moderate; no cash flows; can lag equities for long periods then spike in crises.',
    liquidity: 'High',
    orientation: 'Preservation',
    portfolioRole: 'Hedge',
    useCase: 'Crisis hedge, diversification versus fiat assets, and inflation scepticism—not core growth.',
    examples: 'Gold bullion, gold ETFs, silver coins, platinum ETCs',
    volatility: 'Medium (silver higher than gold)',
    growthPotential: 'Uneven; long episodes of stagnation',
    inflationHedge: 'Moderate–high perception; empirical mixed over all horizons',
    complexity: 'Low–medium (storage/custody for physical)',
    accessibility: 'High via ETFs; medium for vaulted physical',
    holdingPeriod: 'Multi-year strategic hedge sleeve',
    valuationDifficulty: 'No earnings; sentiment and macro driven',
    taxComplexity: 'Often special (VAT on physical in some regions, collectibles rules)',
    deepDive: [
      'Gold frequently behaves differently from equities and bonds, useful as a diversifier rather than return engine.',
      'Storage, insurance, and authenticity matter for physical; ETFs simplify but add counterparty structure.',
    ],
    risk: 40,
    liquidityScore: 88,
    growth: 30,
    income: 0,
    complexityScore: 28,
    accessibilityScore: 82,
    alternativeScore: 22,
  },
  {
    id: 'commodities',
    name: 'Commodities (broad)',
    group: 'traditional',
    definition: 'Raw materials and energy exposures (oil, gas, industrial metals, agriculture) via futures, ETFs, or producer equities.',
    howItWorks: 'Futures roll strategies, index trackers, or indirect equity exposure. Returns driven by supply/demand shocks and inflation cycles.',
    returnDriver: 'Global growth, weather, geopolitics, inventory cycles, and USD.',
    riskProfile: 'Moderate–high; contango can erode futures returns.',
    liquidity: 'High',
    orientation: 'Mixed',
    portfolioRole: 'Hedge',
    useCase: 'Inflation-cycle diversification; not a default core holding for most private wealth plans.',
    examples: 'Broad commodity ETFs, oil futures, copper, agriculture indices',
    volatility: 'High',
    growthPotential: 'Cyclical; no intrinsic “compounding”',
    inflationHedge: 'Moderate–high in some inflation regimes',
    complexity: 'Medium–high (futures mechanics)',
    accessibility: 'Medium–high via funds',
    holdingPeriod: '3–10 years tactical/strategic sleeve',
    valuationDifficulty: 'Medium',
    taxComplexity: 'Futures taxation can differ from equities',
    deepDive: [
      'Commodities can spike with inflation shocks but are volatile and implementation-sensitive.',
    ],
    risk: 58,
    liquidityScore: 85,
    growth: 40,
    income: 10,
    complexityScore: 55,
    accessibilityScore: 70,
    alternativeScore: 30,
  },
  {
    id: 'derivatives',
    name: 'Derivatives',
    group: 'traditional',
    definition: 'Contracts whose value derives from an underlying asset—options, futures, swaps, and CFDs—used to hedge, leverage, or express tactical views.',
    howItWorks: 'Payoffs are defined by contract terms (strike, expiry, notional). Margin and mark-to-market apply. Can replicate or alter exposure without full cash purchase of underlying.',
    returnDriver: 'Underlying price moves, volatility, time decay (options), and financing costs.',
    riskProfile: 'Wide range: hedges can reduce risk; naked/speculative use can create total loss.',
    liquidity: 'High',
    orientation: 'Speculative',
    portfolioRole: 'Tactical',
    useCase: 'Professional hedging, structured risk management, or short-term views—not a standalone wealth-building asset class for most investors.',
    examples: 'Equity index options, interest-rate swaps, commodity futures, FX forwards, CFDs',
    volatility: 'Can be extreme (especially short options or leveraged CFDs)',
    growthPotential: 'Not applicable as a long-term compounding category',
    inflationHedge: 'Depends on underlying',
    complexity: 'High',
    accessibility: 'Medium (retail access varies by product and jurisdiction)',
    holdingPeriod: 'Days to months typically',
    valuationDifficulty: 'High (Greeks, convexity)',
    taxComplexity: 'Often high; character of gains may differ',
    deepDive: [
      'Derivatives are tools, not asset classes in the portfolio-sense: outcomes depend on how they are used.',
      'Leverage, counterparty risk (OTC), and path dependency make education and limits essential.',
      'Suitable for informed hedging or defined-risk structures—not casual speculation with household capital.',
    ],
    risk: 85,
    liquidityScore: 90,
    growth: 15,
    income: 15,
    complexityScore: 92,
    accessibilityScore: 55,
    alternativeScore: 40,
  },
  {
    id: 'real-estate',
    name: 'Real estate',
    group: 'alternative',
    definition: 'Direct property or securitised exposure (REITs, funds) to land and buildings generating rent and/or appreciation.',
    howItWorks: 'Direct ownership involves purchase, maintenance, tenants, and leverage. REITs trade like equities but track property markets. Private funds lock capital for years.',
    returnDriver: 'Rental yield, cap-rate changes, leverage, location, and economic cycle.',
    riskProfile: 'Moderate; illiquidity and concentration rise with direct property.',
    liquidity: 'Medium',
    orientation: 'Mixed',
    portfolioRole: 'Diversifier',
    useCase: 'Income, inflation-linked cash flows, and diversification—size depends on operational appetite.',
    examples: 'Residential buy-to-let, REIT ETFs, logistics funds, co-invest syndicates',
    volatility: 'Medium (listed REITs higher short-term)',
    growthPotential: 'Moderate long-term plus income',
    inflationHedge: 'Moderate (rents often adjust over time)',
    complexity: 'Medium–high direct; lower via listed REITs',
    accessibility: 'Medium (high capital for direct; easy via REITs)',
    holdingPeriod: '7–20+ years direct; liquid sleeve via REITs',
    valuationDifficulty: 'Medium (appraisals, cap rates)',
    taxComplexity: 'Often high (depreciation, local taxes, structuring)',
    deepDive: [
      'Real estate blends bond-like income with equity-like cyclicality; leverage amplifies both.',
      'Listed REITs belong in the diversifier bucket; direct property is an operating business as much as an investment.',
    ],
    risk: 45,
    liquidityScore: 55,
    growth: 55,
    income: 70,
    complexityScore: 60,
    accessibilityScore: 50,
    alternativeScore: 55,
  },
  {
    id: 'infrastructure',
    name: 'Infrastructure',
    group: 'alternative',
    definition: 'Long-life physical or regulated assets—utilities, transport, digital infrastructure—often accessed via private funds or listed proxies.',
    howItWorks: 'Cash flows from contracted or regulated revenues over decades. Private funds lock capital; listed infrastructure equities trade daily.',
    returnDriver: 'Yield, inflation linkage in contracts, utilisation, and rate/discount changes.',
    riskProfile: 'Moderate; regulatory and project risk; illiquid in private form.',
    liquidity: 'Medium–low',
    orientation: 'Income',
    portfolioRole: 'Diversifier',
    useCase: 'Stable income-oriented sleeve for institutions and large portfolios; niche for retail unless via listed funds.',
    examples: 'Listed infrastructure ETFs, private infrastructure funds, renewable project debt',
    volatility: 'Low–medium listed; low reported volatility in appraisals (private)',
    growthPotential: 'Moderate',
    inflationHedge: 'Moderate–high where contracts index to inflation',
    complexity: 'High in private markets',
    accessibility: 'Low–medium (minimums on private funds)',
    holdingPeriod: '10–25 years private; liquid listed sleeve shorter',
    valuationDifficulty: 'High private (appraisal-based)',
    taxComplexity: 'Fund-dependent',
    deepDive: [
      'Infrastructure behaves partly like inflation-linked bonds with growth optionality.',
    ],
    risk: 35,
    liquidityScore: 45,
    growth: 45,
    income: 80,
    complexityScore: 70,
    accessibilityScore: 35,
    alternativeScore: 68,
  },
  {
    id: 'private-markets',
    name: 'Private markets',
    group: 'alternative',
    definition: 'Equity and credit in companies or assets not listed on public exchanges—buyouts, venture, private credit, secondaries.',
    howItWorks: 'Commit capital to funds; drawdowns over years; distributions when assets sell. J-curve reporting; valuations lag public markets.',
    returnDriver: 'Operational improvement, multiple expansion, credit spreads, and illiquidity premium (not guaranteed).',
    riskProfile: 'Moderate–high; dispersion across managers is extreme.',
    liquidity: 'Very low',
    orientation: 'Growth',
    portfolioRole: 'Diversifier',
    useCase: 'Institutional-style diversification and return enhancement for investors who can lock capital 10+ years.',
    examples: 'Buyout funds, growth equity, venture, private credit, co-investments',
    volatility: 'Low reported; true economic volatility deferred',
    growthPotential: 'High dispersion; top quartile vs median gap large',
    inflationHedge: 'Low–moderate',
    complexity: 'Very high',
    accessibility: 'Low (high minimums, accreditation)',
    holdingPeriod: '8–12+ years per fund life',
    valuationDifficulty: 'High (manager marks)',
    taxComplexity: 'High (partnership reporting)',
    deepDive: [
      'Private markets are an access and patience game—manager selection dominates outcomes.',
      'Satellite allocation only for investors who understand lock-up and capital call mechanics.',
    ],
    risk: 60,
    liquidityScore: 12,
    growth: 75,
    income: 25,
    complexityScore: 88,
    accessibilityScore: 22,
    alternativeScore: 85,
  },
  {
    id: 'whisky',
    name: 'Whisky',
    group: 'niche',
    definition: 'Investment in bottled whisky or casks (new-fill or mature) traded among collectors, brokers, and specialist warehouses.',
    howItWorks: 'Value depends on brand, age, rarity, condition, and market fashion. Casks age in bond; bottles require provenance. Sales via auction or specialist dealers.',
    returnDriver: 'Scarcity, brand premium, maturation (casks), collector demand, and market liquidity cycles.',
    riskProfile: 'High idiosyncratic risk; fraud and storage risks; no cash yield.',
    liquidity: 'Low',
    orientation: 'Speculative',
    portfolioRole: 'Passion / collectible',
    useCase: 'Passion allocation with discipline—not a substitute for financial assets.',
    examples: 'Single malt casks in bond, limited releases, vintage bottles with provenance',
    volatility: 'High and opaque',
    growthPotential: 'Episodic; fad-driven segments',
    inflationHedge: 'Weak empirical case',
    complexity: 'High',
    accessibility: 'Low (specialist dealers, authentication)',
    holdingPeriod: '5–20 years casks; bottles variable',
    valuationDifficulty: 'Very high',
    taxComplexity: 'Excise, VAT, and trading character vary by country',
    deepDive: [
      'Storage in duty-suspended warehouses, insurance, and authenticity documentation are non-negotiable.',
      'Cask investing involves angel’s share loss, regauge costs, and exit via bottling or secondary market—not guaranteed appreciation.',
      'Treat as collectible alternative with small sizing and scepticism toward guaranteed-return marketing.',
    ],
    risk: 72,
    liquidityScore: 18,
    growth: 50,
    income: 0,
    complexityScore: 78,
    accessibilityScore: 25,
    alternativeScore: 92,
  },
  {
    id: 'wine',
    name: 'Wine',
    group: 'niche',
    definition: 'Fine wine (typically investment-grade labels) held in bonded storage and traded via merchants, exchanges, or auction.',
    howItWorks: 'Liv-ex indices and merchant pricing guide benchmarks. Condition, storage, and authenticity drive realisable value. No income until sale.',
    returnDriver: 'Critical acclaim, vintage quality, supply constraints, and Asian/US collector demand cycles.',
    riskProfile: 'High; market can stagnate; physical condition risk.',
    liquidity: 'Low',
    orientation: 'Speculative',
    portfolioRole: 'Passion / collectible',
    useCase: 'Collectible diversification for enthusiasts with operational infrastructure.',
    examples: 'Bordeaux first growths, Burgundy, en primeur allocations, bonded portfolios',
    volatility: 'High segment-dependent',
    growthPotential: 'Uneven by region and vintage',
    inflationHedge: 'Weak to moderate anecdotal',
    complexity: 'High',
    accessibility: 'Low–medium (merchants, minimum lots)',
    holdingPeriod: '7–20 years often cited',
    valuationDifficulty: 'Very high',
    taxComplexity: 'VAT, duty, and trading classification',
    deepDive: [
      'Bonded storage, climate control, and insurance are part of total cost of ownership.',
      'Provenance (ex-château, ex-bond) materially affects resale.',
      'Indices can mask dispersion—many labels underperform benchmarks for years.',
    ],
    risk: 68,
    liquidityScore: 22,
    growth: 48,
    income: 0,
    complexityScore: 75,
    accessibilityScore: 30,
    alternativeScore: 90,
  },
  {
    id: 'vsop-spirits',
    name: 'VSOP / collectible spirits',
    group: 'niche',
    definition: 'Luxury aged spirits—cognac, armagnac, rum, and premium aged releases—collected for rarity and brand heritage rather than consumption.',
    howItWorks: 'Similar to whisky/wine collectibles: limited editions, discontinued lines, and auction markets. Distinct from mass-market spirits.',
    returnDriver: 'Brand heritage, age statements, discontinuation, and collector networks.',
    riskProfile: 'High; niche liquidity; authentication critical.',
    liquidity: 'Very low',
    orientation: 'Speculative',
    portfolioRole: 'Passion / collectible',
    useCase: 'Niche passion sleeve; not a portfolio core.',
    examples: 'XO cognac, closed distilleries, commemorative releases, single-barrel proofs',
    volatility: 'High opaque',
    growthPotential: 'Fad and brand dependent',
    inflationHedge: 'Weak',
    complexity: 'High',
    accessibility: 'Very low',
    holdingPeriod: '5–15+ years',
    valuationDifficulty: 'Very high',
    taxComplexity: 'Excise and import rules',
    deepDive: [
      'Distinguish investable collectibles from consumer products—liquidity is far thinner than mainstream spirits retail.',
      'Storage upright, light protection, and provenance documentation mirror other luxury collectibles.',
    ],
    risk: 75,
    liquidityScore: 15,
    growth: 42,
    income: 0,
    complexityScore: 80,
    accessibilityScore: 18,
    alternativeScore: 94,
  },
  {
    id: 'collectibles',
    name: 'Collectibles (broad)',
    group: 'niche',
    definition: 'Tangible assets collected for rarity and demand—art, watches, classic cars, coins, memorabilia—outside standard financial markets.',
    howItWorks: 'Markets are fragmented; pricing via auction houses and dealers. High transaction costs; expertise edge dominates.',
    returnDriver: 'Scarcity, cultural trends, condition, and collector liquidity.',
    riskProfile: 'Very high dispersion; many categories lose money after costs.',
    liquidity: 'Very low',
    orientation: 'Speculative',
    portfolioRole: 'Passion / collectible',
    useCase: 'Personal interest with strict position limits—not wealth-planning core.',
    examples: 'Contemporary art, Rolex sport models, classic Porsches, rare coins',
    volatility: 'Extreme segment-dependent',
    growthPotential: 'Unpredictable; winner-take-all within category',
    inflationHedge: 'Anecdotal only',
    complexity: 'Very high',
    accessibility: 'Low',
    holdingPeriod: 'Highly variable',
    valuationDifficulty: 'Very high',
    taxComplexity: 'Often complex (collectibles rates, VAT)',
    deepDive: [
      'Umbrella category: whisky, wine, and spirits are subsets—each with distinct market infrastructure.',
      'Fraud, restoration, and insurance gaps are common failure modes.',
    ],
    risk: 78,
    liquidityScore: 10,
    growth: 45,
    income: 0,
    complexityScore: 85,
    accessibilityScore: 20,
    alternativeScore: 96,
  },
  {
    id: 'weather',
    name: 'Weather-related investments',
    group: 'niche',
    definition: 'Instruments linked to weather outcomes—derivatives on temperature/rainfall, catastrophe bonds, climate-risk transfers—or funds with weather-linked payoffs.',
    howItWorks: 'Often structured as derivatives with payouts tied to indices (heating degree days, rainfall). Cat bonds transfer insurance risk to capital markets. Not a retail shelf product.',
    returnDriver: 'Weather realisations vs strike, insurance pricing, and reinsurance spreads—not economic growth.',
    riskProfile: 'Specialised; basis risk; model risk; low transparency for non-experts.',
    liquidity: 'Low',
    orientation: 'Speculative',
    portfolioRole: 'Tactical',
    useCase: 'Corporate hedging (energy, agriculture) or institutional alternative risk premia—not mainstream personal investing.',
    examples: 'Weather derivatives, catastrophe bonds, climate-linked reinsurance sidecars',
    volatility: 'High event-driven',
    growthPotential: 'Not a compounding wealth asset',
    inflationHedge: 'Indirect at best',
    complexity: 'Very high',
    accessibility: 'Very low',
    holdingPeriod: 'Seasonal to multi-year structures',
    valuationDifficulty: 'Very high',
    taxComplexity: 'Highly specialised',
    deepDive: [
      'Category spans risk transfer for insurers and hedgers—not “investing in weather” in a retail sense.',
      'Understanding counterparty, index construction, and basis risk is essential.',
      'Treat as institutional/advanced exposure, not a satellite retail allocation.',
    ],
    risk: 80,
    liquidityScore: 20,
    growth: 20,
    income: 40,
    complexityScore: 95,
    accessibilityScore: 8,
    alternativeScore: 88,
  },
  {
    id: 'crypto',
    name: 'Crypto (digital assets)',
    group: 'niche',
    definition: 'Digital bearer assets on decentralised or platform networks—Bitcoin, Ethereum, and thousands of tokens—with varying economics and governance.',
    howItWorks: 'Self-custody or exchange custody; keys secure ownership. Returns from adoption, monetary premium, staking yields (where applicable), and speculation. Protocol risk is real.',
    returnDriver: 'Liquidity cycles, regulation, adoption, halving narratives, and risk appetite—not cash-flow fundamentals for most tokens.',
    riskProfile: 'Very high volatility; total loss possible (fraud, hacks, protocol failure).',
    liquidity: 'High',
    orientation: 'Speculative',
    portfolioRole: 'Speculative',
    useCase: 'High-risk satellite only for investors who accept volatility, custody, and regulatory evolution.',
    examples: 'Bitcoin, Ethereum, stablecoins (not investments), tokenised assets',
    volatility: 'Very high',
    growthPotential: 'Uncertain; boom-bust cycles',
    inflationHedge: 'Debated; not proven like gold over long institutional horizons',
    complexity: 'Medium–high (custody, tax lots, DeFi risks)',
    accessibility: 'High via exchanges; custody is the bottleneck',
    holdingPeriod: 'Highly variable; often shorter than equities in practice',
    valuationDifficulty: 'Very high (no universal model)',
    taxComplexity: 'High and evolving (staking, airdrops, cross-border)',
    deepDive: [
      'Separate technology interest from position sizing—many tokens are speculative securities in practice.',
      'Custody (hardware, multisig, exchange risk) and regulatory classification dominate outcomes as much as price charts.',
      'Not a replacement for diversified financial assets; if used, size as high-volatility satellite with clear exit and tax plan.',
    ],
    risk: 92,
    liquidityScore: 88,
    growth: 70,
    income: 15,
    complexityScore: 72,
    accessibilityScore: 88,
    alternativeScore: 75,
  },
];

export const PORTFOLIO_GROUPS = [
  {
    id: 'core',
    title: 'Core assets',
    description: 'Strategic long-term holdings that anchor return and risk budgets.',
    categoryIds: ['global-equities'],
  },
  {
    id: 'income',
    title: 'Income / defensive assets',
    description: 'Stabilise drawdowns and fund near-term liabilities.',
    categoryIds: ['fixed-income', 'cash', 'infrastructure'],
  },
  {
    id: 'diversifiers',
    title: 'Diversifiers',
    description: 'Improve portfolio efficiency via different return drivers and cycles.',
    categoryIds: ['real-estate', 'private-markets', 'commodities'],
  },
  {
    id: 'hedges',
    title: 'Inflation & crisis hedges',
    description: 'May lag for years but can matter in specific macro regimes.',
    categoryIds: ['precious-metals', 'commodities', 'infrastructure'],
  },
  {
    id: 'tactical',
    title: 'Tactical / speculative tools',
    description: 'Short horizon or leverage-sensitive—not default wealth-building blocks.',
    categoryIds: ['fx', 'derivatives', 'weather', 'crypto'],
  },
  {
    id: 'passion',
    title: 'Passion / collectible assets',
    description: 'Enjoyment-driven with financial upside uncertain—strict size limits.',
    categoryIds: ['whisky', 'wine', 'vsop-spirits', 'collectibles'],
  },
] as const;

export const SUITABILITY_GOALS = [
  {
    id: 'wealth',
    title: 'Wealth building',
    description: 'Multi-decade compounding with acceptable drawdowns.',
    fit: ['global-equities', 'private-markets', 'real-estate'],
    caution: ['crypto', 'fx', 'derivatives', 'collectibles'],
  },
  {
    id: 'income',
    title: 'Income generation',
    description: 'Cash flow for spending or retirement drawdown support.',
    fit: ['fixed-income', 'real-estate', 'infrastructure', 'cash'],
    caution: ['growth-only collectibles', 'weather', 'leveraged derivatives'],
  },
  {
    id: 'preservation',
    title: 'Capital preservation',
    description: 'Limit permanent loss of nominal capital.',
    fit: ['cash', 'fixed-income', 'short-duration government debt'],
    caution: ['crypto', 'speculative FX', 'illiquid collectibles'],
  },
  {
    id: 'inflation',
    title: 'Inflation protection',
    description: 'Maintain purchasing power through price shocks.',
    fit: ['precious-metals', 'commodities', 'inflation-linked bonds', 'real-estate'],
    caution: ['long nominal bonds in rising-rate regimes', 'cash'],
  },
  {
    id: 'diversification',
    title: 'Diversification',
    description: 'Reduce reliance on a single risk factor.',
    fit: ['precious-metals', 'real-estate', 'commodities', 'global-equities'],
    caution: ['concentrated collectibles', 'single-stock crypto'],
  },
  {
    id: 'speculation',
    title: 'Speculation',
    description: 'Accept high variance for asymmetric upside—explicitly sized small.',
    fit: ['crypto', 'fx', 'derivatives', 'venture-style private markets'],
    caution: ['confusing speculation with core allocation'],
  },
  {
    id: 'passion',
    title: 'Passion / interest',
    description: 'Non-financial utility matters; returns are secondary.',
    fit: ['wine', 'whisky', 'vsop-spirits', 'collectibles'],
    caution: ['illiquidity, fraud, storage costs'],
  },
] as const;

export const RISK_WARNINGS = [
  {
    title: 'Illiquidity',
    body: 'Alternative and collectible markets can freeze in stress—forced sales destroy value. Size positions assuming you cannot exit quickly.',
  },
  {
    title: 'Valuation uncertainty',
    body: 'Opaque marks, appraisal lag, and narrative pricing make true risk hard to measure until you sell.',
  },
  {
    title: 'Storage & custody',
    body: 'Physical assets, crypto keys, and casks in bond require insurance, audits, and operational discipline—costs erode returns.',
  },
  {
    title: 'Counterparty risk',
    body: 'Exchanges, brokers, warehouses, and OTC dealers can fail. Understand who holds title and who backs guarantees.',
  },
  {
    title: 'Leverage risk',
    body: 'Derivatives, FX, and property debt magnify losses. Stress outcomes before sizing.',
  },
  {
    title: 'Regulation & tax',
    body: 'Classification changes (especially crypto and cross-border assets) can alter after-tax returns abruptly.',
  },
  {
    title: 'Authenticity & fraud',
    body: 'Collectible markets attract counterfeits and misrepresentation—expert verification is part of due diligence.',
  },
  {
    title: 'Concentration',
    body: 'Single names, single vintages, or single protocols dominate outcomes. Satellites should remain satellites.',
  },
] as const;

export const COMPARISON_ROWS: { key: keyof InvestmentCategory | 'name'; label: string }[] = [
  { key: 'definition', label: 'Definition' },
  { key: 'examples', label: 'Examples' },
  { key: 'liquidity', label: 'Liquidity' },
  { key: 'volatility', label: 'Volatility' },
  { key: 'orientation', label: 'Income vs growth' },
  { key: 'growthPotential', label: 'Long-term growth' },
  { key: 'inflationHedge', label: 'Inflation hedge' },
  { key: 'complexity', label: 'Complexity' },
  { key: 'accessibility', label: 'Accessibility' },
  { key: 'holdingPeriod', label: 'Typical holding period' },
  { key: 'valuationDifficulty', label: 'Valuation difficulty' },
  { key: 'taxComplexity', label: 'Tax / reporting (indicative)' },
  { key: 'portfolioRole', label: 'Portfolio role' },
];
